// app/projects/page.tsx
'use client';

import React, { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';
import { Rocket, User, ArrowRight, Plus, X, AlertCircle, Settings2, CheckCircle2, AlertTriangle, HelpCircle } from 'lucide-react';
import NavigationLayout from '@/components/NavigationLayout';
import Link from 'next/link';
import { cn } from '@/lib/utils';

export default function ProjectsPage() {
  const [projects, setProjects] = useState<any[]>([]);
  const [currentUser, setCurrentUser] = useState<any>(null);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [loading, setLoading] = useState(true);
  const [users, setUsers] = useState<any[]>([]);
  const [formData, setFormData] = useState({
    id: '',
    name: '',
    commander_id: '',
    director_id: '',
    planned_progress: 0,
    planned_cost: 0,
    collected_amount: 0,
    receivable_amount: 0
  });

  const columns = [
    { id: 'stt', label: 'STT', alwaysVisible: true },
    { id: 'name', label: 'Công trình', alwaysVisible: true },
    { id: 'status', label: 'Trạng thái', alwaysVisible: true },
    { id: 'commander', label: 'Chỉ huy trưởng' },
    { id: 'director', label: 'PGĐ phụ trách' },
    { id: 'planned_progress', label: 'Mục tiêu tiến độ (%)' },
    { id: 'actual_progress', label: 'Tiến độ thực tế (%)' },
    { id: 'progress_variance', label: 'Lệch tiến độ' },
    { id: 'planned_cost', label: 'Ngân sách mục tiêu' },
    { id: 'actual_cost', label: 'Chi phí thực tế' },
    { id: 'cost_variance', label: 'Lệch chi phí' },
    { id: 'collected_amount', label: 'Đã thu' },
    { id: 'receivable_amount', label: 'Phải thu' },
    { id: 'actions', label: 'Thao tác', alwaysVisible: true },
  ];

  const [visibleColumns, setVisibleColumns] = useState<string[]>(columns.map(c => c.id));
  const [showColumnToggle, setShowColumnToggle] = useState(false);

  const getStatus = (p: any) => {
    const isRisk = (p.planned_progress - p.actual_progress > 5) || (p.actual_cost > p.planned_cost * 1.1);
    if (isRisk) return { label: '🔴 Nguy cơ', color: 'text-error' };
    
    const isWarning = (p.planned_progress > p.actual_progress) || (p.actual_cost > p.planned_cost);
    if (isWarning) return { label: '🟡 Cảnh báo', color: 'text-amber-500' };
    
    return { label: '🟢 Bình thường', color: 'text-emerald-500' };
  };
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  useEffect(() => {
    async function fetchData() {
      setLoading(true);
      const { data: { session } } = await supabase.auth.getSession();
      
      if (session) {
        // Get user profile
        const { data: profile } = await supabase
          .from('users')
          .select('*')
          .eq('id', session.user.id)
          .single();
        
        setCurrentUser(profile);

        // Fetch projects
        const { data: projectsData } = await supabase
          .from('projects')
          .select(`
            *,
            commander:users!projects_commander_id_fkey(name),
            director:users!projects_director_id_fkey(name),
            reports:daily_reports(progress_percent, actual_cost)
          `);

        if (projectsData) {
          setProjects(projectsData.map(p => {
            const actual_progress = p.reports && p.reports.length > 0 
              ? Math.max(0, ...p.reports.map((r: any) => typeof r.progress_percent === 'number' ? r.progress_percent : 0)) 
              : 0;
            const actual_cost = p.reports 
              ? p.reports.reduce((acc: number, r: any) => acc + (typeof r.actual_cost === 'number' ? r.actual_cost : 0), 0) 
              : 0;
            
            return {
              ...p,
              actual_progress,
              actual_cost,
              progress_variance: actual_progress - p.planned_progress,
              cost_variance: actual_cost - p.planned_cost,
              commander_name: p.commander?.name,
              director_name: p.director?.name
            };
          }));
        }

        // Fetch all users for selection
        const { data: allUsers } = await supabase.from('users').select('*');
        if (allUsers) setUsers(allUsers);
      }
      setLoading(false);
    }
    fetchData();
  }, []);

  const handleOpenCreate = () => {
    setIsEditing(false);
    setFormData({
      id: '',
      name: '',
      commander_id: '',
      director_id: '',
      planned_progress: 0,
      planned_cost: 0,
      collected_amount: 0,
      receivable_amount: 0
    });
    setShowCreateModal(true);
  };

  const handleOpenEdit = (project: any) => {
    setIsEditing(true);
    setFormData({
      id: project.id,
      name: project.name,
      commander_id: project.commander_id,
      director_id: project.director_id,
      planned_progress: project.planned_progress,
      planned_cost: project.planned_cost,
      collected_amount: project.collected_amount || 0,
      receivable_amount: project.receivable_amount || 0
    });
    setShowCreateModal(true);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setErrorMsg(null);

    const { error } = isEditing 
      ? await supabase.from('projects').update({
          name: formData.name,
          commander_id: formData.commander_id,
          director_id: formData.director_id,
          planned_progress: formData.planned_progress,
          planned_cost: formData.planned_cost,
          collected_amount: formData.collected_amount,
          receivable_amount: formData.receivable_amount
        }).eq('id', formData.id)
      : await supabase.from('projects').insert([formData]);

    if (error) {
      setErrorMsg(error.message);
      if (error.message.includes("permission denied")) {
        setErrorMsg("LỖI PHÂN QUYỀN: Bạn chưa được cấp quyền trên bảng Projects trong Supabase Dashboard.");
      }
    } else {
      setShowCreateModal(false);
      // Refresh list
      window.location.reload();
    }
  };

  const isAuthorized = currentUser?.role === 'admin' || currentUser?.role === 'PGD';

  return (
    <NavigationLayout activeTab="projects">
      <div className="space-y-8 animate-in slide-in-from-bottom duration-500">
        <div className="flex justify-between items-end">
          <div>
            <h2 className="text-3xl font-bold text-primary tracking-tight">Công trình đang hoạt động</h2>
            <p className="text-on-surface-variant mt-1">Giám sát danh mục qua Supabase.</p>
          </div>
          <div className="flex items-center gap-3">
            <div className="relative">
              <button 
                onClick={() => setShowColumnToggle(!showColumnToggle)}
                className="p-3 bg-surface-container-low rounded-xl border border-outline-variant hover:bg-surface-container-high transition-all"
                title="Tùy chỉnh cột"
              >
                <Settings2 className="w-5 h-5 text-on-surface-variant" />
              </button>
              
              {showColumnToggle && (
                <div className="absolute right-0 mt-2 w-64 bg-white border border-outline-variant rounded-xl shadow-2xl z-50 p-4 animate-in fade-in zoom-in-95 duration-200">
                   <div className="flex justify-between items-center mb-4 border-b border-outline-variant pb-2">
                      <h4 className="font-black text-[10px] uppercase tracking-widest text-primary">Hiển thị cột</h4>
                      <X className="w-4 h-4 cursor-pointer text-on-surface-variant" onClick={() => setShowColumnToggle(false)} />
                   </div>
                   <div className="space-y-2 max-h-60 overflow-y-auto">
                      {columns.map(col => (
                        <label key={col.id} className={cn("flex items-center gap-3 p-2 rounded-lg hover:bg-surface-container-low cursor-pointer transition-colors", col.alwaysVisible && "opacity-50 pointer-events-none")}>
                          <input 
                            type="checkbox"
                            checked={visibleColumns.includes(col.id)}
                            onChange={(e) => {
                              if (e.target.checked) setVisibleColumns([...visibleColumns, col.id]);
                              else setVisibleColumns(visibleColumns.filter(c => c !== col.id));
                            }}
                            className="w-4 h-4 rounded border-outline text-primary focus:ring-primary"
                          />
                          <span className="text-xs font-bold text-on-surface">{col.label}</span>
                        </label>
                      ))}
                   </div>
                </div>
              )}
            </div>
            {isAuthorized && (
              <button 
                onClick={handleOpenCreate}
                className="bg-primary text-white px-6 py-3 rounded-xl font-bold flex items-center gap-2 hover:bg-primary/90 transition-all shadow-lg"
              >
                <Plus className="w-5 h-5" />
                DỰ ÁN MỚI
              </button>
            )}
          </div>
        </div>

        {loading ? (
          <div className="flex justify-center p-12">
            <div className="w-12 h-12 border-4 border-primary border-t-transparent rounded-full animate-spin"></div>
          </div>
        ) : (
          <div className="bg-white rounded-xl border border-outline-variant shadow-sm overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead className="bg-surface-container-low border-b border-outline-variant">
                <tr>
                  {columns.filter(c => visibleColumns.includes(c.id)).map(col => (
                    <th key={col.id} className="px-4 py-4 text-[10px] font-bold text-on-surface-variant uppercase tracking-widest whitespace-nowrap">
                      {col.label}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-outline-variant">
                {projects.map((p, idx) => {
                  const status = getStatus(p);
                  return (
                    <tr key={p.id} className="hover:bg-surface-container-low transition-colors group">
                      {visibleColumns.includes('stt') && <td className="px-4 py-4 text-xs font-mono text-on-surface-variant">{idx + 1}</td>}
                      {visibleColumns.includes('name') && <td className="px-4 py-4 font-bold text-primary min-w-[200px]">{p.name}</td>}
                      {visibleColumns.includes('status') && (
                        <td className="px-4 py-4 whitespace-nowrap">
                          <span className={cn("text-xs font-black uppercase tracking-tighter", status.color)}>
                            {status.label}
                          </span>
                        </td>
                      )}
                      {visibleColumns.includes('commander') && (
                        <td className="px-4 py-4 text-sm whitespace-nowrap">
                          <div className="flex items-center gap-2">
                             <User className="w-3 h-3 opacity-30" />
                             {p.commander_name || 'Chưa phân công'}
                          </div>
                        </td>
                      )}
                      {visibleColumns.includes('director') && (
                        <td className="px-4 py-4 text-sm whitespace-nowrap">
                          <div className="flex items-center gap-2">
                             <User className="w-3 h-3 opacity-30" />
                             {p.director_name || 'Chưa phân công'}
                          </div>
                        </td>
                      )}
                      {visibleColumns.includes('planned_progress') && <td className="px-4 py-4 text-center font-bold text-sm">{p.planned_progress}%</td>}
                      {visibleColumns.includes('actual_progress') && (
                        <td className="px-4 py-4">
                           <div className="flex flex-col items-center gap-1 min-w-[100px]">
                              <span className="text-[10px] font-bold text-primary">{p.actual_progress || 0}%</span>
                              <div className="w-16 h-1.5 bg-surface-container-highest rounded-full overflow-hidden">
                                 <div className="h-full bg-primary" style={{ width: `${isNaN(p.actual_progress) ? 0 : p.actual_progress}%` }}></div>
                              </div>
                           </div>
                        </td>
                      )}
                      {visibleColumns.includes('progress_variance') && (
                        <td className={cn("px-4 py-4 text-center font-black text-sm", p.progress_variance < 0 ? 'text-error' : 'text-emerald-500')}>
                          {p.progress_variance > 0 ? '+' : ''}{p.progress_variance}%
                        </td>
                      )}
                      {visibleColumns.includes('planned_cost') && <td className="px-4 py-4 text-right font-bold text-sm whitespace-nowrap">${(p.planned_cost / 1000).toFixed(0)}k</td>}
                      {visibleColumns.includes('actual_cost') && <td className="px-4 py-4 text-right font-bold text-sm whitespace-nowrap text-primary">${(p.actual_cost / 1000).toFixed(0)}k</td>}
                      {visibleColumns.includes('cost_variance') && (
                        <td className={cn("px-4 py-4 text-right font-black text-sm whitespace-nowrap", p.cost_variance > 0 ? 'text-error' : 'text-emerald-500')}>
                          {p.cost_variance > 0 ? '+' : ''}${(p.cost_variance / 1000).toFixed(0)}k
                        </td>
                      )}
                      {visibleColumns.includes('collected_amount') && <td className="px-4 py-4 text-right font-bold text-sm whitespace-nowrap">${(p.collected_amount / 1000).toFixed(0)}k</td>}
                      {visibleColumns.includes('receivable_amount') && <td className="px-4 py-4 text-right font-bold text-sm whitespace-nowrap text-secondary">${(p.receivable_amount / 1000).toFixed(0)}k</td>}
                      {visibleColumns.includes('actions') && (
                        <td className="px-4 py-4">
                          <div className="flex items-center justify-center gap-3">
                            <Link href={`/projects/${p.id}`} className="p-2 hover:bg-primary/10 rounded-lg text-primary transition-colors">
                              <ArrowRight className="w-4 h-4" />
                            </Link>
                            {isAuthorized && (
                              <button 
                                onClick={() => handleOpenEdit(p)}
                                className="p-2 hover:bg-secondary/10 rounded-lg text-secondary transition-colors"
                              >
                                Sửa
                              </button>
                            )}
                          </div>
                        </td>
                      )}
                    </tr>
                  );
                })}
                {projects.length === 0 && (
                  <tr>
                    <td colSpan={visibleColumns.length} className="px-6 py-12 text-center text-on-surface-variant opacity-50 italic">
                      Không tìm thấy dự án nào.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        )}

        {/* Create Modal */}
        {showCreateModal && (
          <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
            <div className="bg-white w-full max-w-lg rounded-2xl shadow-2xl overflow-hidden animate-in zoom-in-95 duration-200">
              <div className="px-8 py-6 border-b border-outline-variant flex justify-between items-center bg-surface-container-low">
                <h3 className="text-xl font-black text-primary tracking-tight">
                  {isEditing ? 'CHỈNH SỬA DỰ ÁN CHIẾN LƯỢC' : 'DỰ ÁN CHIẾN LƯỢC MỚI'}
                </h3>
                <button onClick={() => setShowCreateModal(false)} className="text-on-surface-variant hover:text-primary transition-colors">
                  <X className="w-6 h-6" />
                </button>
              </div>
              <form onSubmit={handleSubmit} className="p-8 space-y-5">
                <div className="grid grid-cols-1 gap-5">
                  <div className="space-y-1.5">
                    <label className="text-[10px] font-bold text-on-surface-variant uppercase tracking-widest pl-1">Mã dự án (ID)</label>
                    <input 
                      required
                      disabled={isEditing}
                      placeholder="VD: P2024-001"
                      className={cn(
                        "w-full bg-surface-container-low border border-outline px-4 py-3 rounded-xl focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition-all uppercase",
                        isEditing && "opacity-50 cursor-not-allowed bg-surface-container-highest"
                      )}
                      value={formData.id}
                      onChange={e => setFormData({...formData, id: e.target.value.toUpperCase()})}
                    />
                  </div>
                  <div className="space-y-1.5">
                    <label className="text-[10px] font-bold text-on-surface-variant uppercase tracking-widest pl-1">Tên đầy đủ dự án</label>
                    <input 
                      required
                      placeholder="Nhập tên dự án xây dựng"
                      className="w-full bg-surface-container-low border border-outline px-4 py-3 rounded-xl focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition-all"
                      value={formData.name}
                      onChange={e => setFormData({...formData, name: e.target.value})}
                    />
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-5">
                  <div className="space-y-1.5">
                    <label className="text-[10px] font-bold text-on-surface-variant uppercase tracking-widest pl-1">Chỉ huy trưởng (BCH)</label>
                    <select 
                      required
                      className="w-full bg-surface-container-low border border-outline px-4 py-3 rounded-xl focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition-all"
                      value={formData.commander_id}
                      onChange={e => setFormData({...formData, commander_id: e.target.value})}
                    >
                      <option value="">Chọn BCH</option>
                      {users.filter(u => u.role === 'BCH' || u.role === 'admin').map(u => (
                        <option key={u.id} value={u.id}>{u.name} ({u.role})</option>
                      ))}
                    </select>
                  </div>
                  <div className="space-y-1.5">
                    <label className="text-[10px] font-bold text-on-surface-variant uppercase tracking-widest pl-1">Giám đốc (PGĐ)</label>
                    <select 
                      required
                      className="w-full bg-surface-container-low border border-outline px-4 py-3 rounded-xl focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition-all"
                      value={formData.director_id}
                      onChange={e => setFormData({...formData, director_id: e.target.value})}
                    >
                      <option value="">Chọn PGĐ</option>
                      {users.filter(u => u.role === 'PGD' || u.role === 'admin').map(u => (
                        <option key={u.id} value={u.id}>{u.name} ({u.role})</option>
                      ))}
                    </select>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-5">
                  <div className="space-y-1.5">
                    <label className="text-[10px] font-bold text-on-surface-variant uppercase tracking-widest pl-1">Mục tiêu tiến độ (%)</label>
                    <input 
                      type="number"
                      required
                      min="0"
                      max="100"
                      className="w-full bg-surface-container-low border border-outline px-4 py-3 rounded-xl focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition-all"
                      value={formData.planned_progress}
                      onChange={e => setFormData({...formData, planned_progress: parseFloat(e.target.value)})}
                    />
                  </div>
                  <div className="space-y-1.5">
                    <label className="text-[10px] font-bold text-on-surface-variant uppercase tracking-widest pl-1">Ngân sách mục tiêu ($)</label>
                    <input 
                      type="number"
                      required
                      min="0"
                      className="w-full bg-surface-container-low border border-outline px-4 py-3 rounded-xl focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition-all"
                      value={formData.planned_cost}
                      onChange={e => setFormData({...formData, planned_cost: parseInt(e.target.value)})}
                    />
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-5">
                  <div className="space-y-1.5">
                    <label className="text-[10px] font-bold text-on-surface-variant uppercase tracking-widest pl-1">Đã thu ($)</label>
                    <input 
                      type="number"
                      required
                      min="0"
                      className="w-full bg-surface-container-low border border-outline px-4 py-3 rounded-xl focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition-all"
                      value={formData.collected_amount}
                      onChange={e => setFormData({...formData, collected_amount: parseInt(e.target.value) || 0})}
                    />
                  </div>
                  <div className="space-y-1.5">
                    <label className="text-[10px] font-bold text-on-surface-variant uppercase tracking-widest pl-1">Phải thu ($)</label>
                    <input 
                      type="number"
                      required
                      min="0"
                      className="w-full bg-surface-container-low border border-outline px-4 py-3 rounded-xl focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition-all"
                      value={formData.receivable_amount}
                      onChange={e => setFormData({...formData, receivable_amount: parseInt(e.target.value) || 0})}
                    />
                  </div>
                </div>

                {errorMsg && (
                  <div className="flex items-center gap-2 p-3 bg-error-container/20 border border-error/30 rounded-xl text-error text-[11px] font-bold">
                    <AlertCircle className="w-4 h-4 shrink-0" />
                    <p>{errorMsg}</p>
                  </div>
                )}

                <div className="pt-4">
                  <button 
                    type="submit"
                    className="w-full bg-primary text-white py-4 rounded-xl font-black tracking-widest hover:bg-primary/90 transition-all shadow-xl uppercase text-sm"
                  >
                    {isEditing ? 'Cập nhật chiến lược' : 'Cấp phép & Triển khai'}
                  </button>
                </div>
              </form>
            </div>
          </div>
        )}
      </div>
    </NavigationLayout>
  );
}

// src/views/Projects.vue
<template>
  <NavigationLayout active-tab="projects">
    <div class="space-y-8 animate-in fade-in duration-500">
      <div class="flex justify-between items-center">
         <div>
            <h1 class="text-2xl font-black text-primary uppercase">DANH MỤC DỰ ÁN</h1>
            <p class="text-sm text-on-surface-variant font-medium">Theo dõi tiến độ hợp đồng & tài chính</p>
         </div>
         <button 
           v-if="can('create', 'projects')"
           @click="isModalOpen = true"
           class="px-6 py-3 bg-primary text-white rounded-xl font-bold flex items-center gap-2 shadow-xl shadow-primary/20 hover:-translate-y-0.5 transition-all"
         >
            <Plus class="w-5 h-5" />
            TẠO DỰ ÁN MỚI
         </button>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
         <template v-if="loading">
           <div v-for="i in 3" :key="i" class="h-48 bg-white rounded-2xl animate-pulse border border-outline-variant" />
         </template>
         <template v-else>
           <router-link 
             v-for="p in projects"
             :key="p.id"
             :to="`/projects/detail?id=${p.id}`" 
             class="bg-white p-6 rounded-2xl border border-outline-variant shadow-sm hover:shadow-xl hover:border-primary/30 transition-all group"
           >
              <div class="flex justify-between items-start mb-4">
                 <div class="w-12 h-12 bg-primary/5 rounded-2xl flex items-center justify-center group-hover:bg-primary group-hover:text-white transition-colors">
                    <Rocket class="w-6 h-6 text-primary group-hover:text-white" />
                 </div>
                 <div class="text-right space-y-2">
                    <div>
                      <p class="text-[9px] font-black uppercase text-on-surface-variant tracking-widest leading-none">Giá trị HĐ</p>
                      <p class="text-sm font-black text-primary mt-1">${{ (p.contract_value || 0).toLocaleString() }}</p>
                    </div>
                    <div v-if="p.status_evaluation" 
                       class="px-2 py-0.5 rounded text-[8px] font-black uppercase tracking-tighter inline-block text-white"
                       :class="[
                         p.status_evaluation === 'RISK' ? 'bg-red-500' :
                         p.status_evaluation === 'WARNING' ? 'bg-amber-500' : 'bg-emerald-500'
                       ]"
                    >
                      {{ p.status_evaluation }}
                    </div>
                 </div>
              </div>
              <div class="flex items-start justify-between gap-4 min-h-[3.5rem]">
                 <h3 class="text-lg font-black text-primary uppercase leading-tight line-clamp-2">{{ p.name }}</h3>
                 <button v-if="can('delete', 'projects')" @click.prevent="deleteProject(p.id)" class="text-red-500/50 hover:text-red-600 hover:bg-red-50 p-2 rounded-full transition-colors" title="Xóa dự án">
                    <Trash2 class="w-4 h-4" />
                 </button>
              </div>
              
              <div class="mt-4 pt-4 border-t border-outline-variant/30 grid grid-cols-2 gap-4">
                 <div>
                    <p class="text-[8px] font-black uppercase text-on-surface-variant tracking-widest">Bắt đầu</p>
                    <p class="text-xs font-bold text-on-surface">{{ p.start_date ? new Date(p.start_date).toLocaleDateString('vi-VN') : '---' }}</p>
                 </div>
                 <div>
                    <p class="text-[8px] font-black uppercase text-on-surface-variant tracking-widest text-right">Dự kiến kết thúc</p>
                    <p class="text-xs font-bold text-primary text-right">{{ p.expected_end_date ? new Date(p.expected_end_date).toLocaleDateString('vi-VN') : '---' }}</p>
                 </div>
              </div>
              
              <div class="mt-4 flex items-center justify-between">
                 <div class="flex -space-x-2">
                     <div class="w-6 h-6 rounded-full bg-surface-container border border-white flex items-center justify-center text-[8px] font-bold text-on-surface-variant">
                        <Users class="w-3 h-3" />
                     </div>
                 </div>
                 <div class="flex items-center gap-1 text-[10px] font-black text-primary opacity-50 group-hover:opacity-100 transition-opacity">
                    CHI TIẾT <ArrowRight class="w-3 h-3" />
                 </div>
              </div>
           </router-link>
         </template>
      </div>

      <div v-if="isModalOpen" class="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/40 backdrop-blur-sm">
         <div class="bg-white w-full max-w-2xl rounded-3xl shadow-2xl overflow-hidden animate-in zoom-in-95 duration-200">
            <div class="p-8 border-b border-outline-variant flex items-center justify-between bg-surface-container-low/30">
               <div>
                  <h2 class="text-2xl font-black text-primary uppercase tracking-tight">KHỞI TẠO DỰ ÁN</h2>
                  <p class="text-xs text-on-surface-variant font-bold uppercase tracking-widest mt-1">Thiết lập thông tin hợp đồng cơ sở</p>
               </div>
               <button @click="isModalOpen = false" class="w-10 h-10 rounded-full hover:bg-white flex items-center justify-center text-on-surface-variant transition-colors">
                  <X class="w-6 h-6" />
               </button>
            </div>
            
            <form @submit.prevent="handleSubmit" class="p-8 space-y-6">
               <div class="space-y-2">
                  <label class="text-[10px] font-black text-on-surface-variant uppercase tracking-widest pl-1">Tên dự án / Công trình</label>
                  <input 
                    type="text" required
                    class="w-full p-4 bg-surface-container-low border border-outline rounded-2xl font-bold focus:ring-2 focus:ring-primary outline-none"
                    placeholder="VD: Cầu Mỹ Thuận 2 - Gói thầu XL01"
                    v-model="formData.name"
                  />
               </div>

               <div class="grid grid-cols-2 gap-6">
                  <div class="space-y-2">
                     <label class="text-[10px] font-black text-on-surface-variant uppercase tracking-widest pl-1 flex items-center gap-2">
                        <DollarSign class="w-3 h-3" />
                        Giá trị hợp đồng ($)
                     </label>
                     <input 
                       type="number" required
                       class="w-full p-4 bg-surface-container-low border border-outline rounded-2xl font-black text-primary text-xl"
                       v-model.number="formData.contract_value"
                     />
                  </div>
                  <div class="space-y-2">
                     <label class="text-[10px] font-black text-on-surface-variant uppercase tracking-widest pl-1 flex items-center gap-2 text-emerald-600">
                        Số tiền tạm ứng (30%)
                     </label>
                     <div class="w-full p-4 bg-emerald-50 border border-emerald-100 rounded-2xl font-black text-emerald-600 text-xl">
                        ${{ (formData.contract_value * formData.advance_rate).toLocaleString() }}
                     </div>
                  </div>
               </div>

               <div class="grid grid-cols-2 gap-6">
                  <div class="space-y-2">
                     <label class="text-[10px] font-black text-on-surface-variant uppercase tracking-widest pl-1 flex items-center gap-2">
                        <Calendar class="w-3 h-3" />
                        Ngày bắt đầu
                     </label>
                     <input 
                       type="date" required
                       class="w-full p-4 bg-surface-container-low border border-outline rounded-xl font-bold"
                       v-model="formData.start_date"
                     />
                  </div>
                  <div class="space-y-2">
                     <label class="text-[10px] font-black text-on-surface-variant uppercase tracking-widest pl-1 flex items-center gap-2">
                        <Calendar class="w-3 h-3" />
                        Dự kiến kết thúc
                     </label>
                     <input 
                       type="date" required
                       class="w-full p-4 bg-surface-container-low border border-outline rounded-xl font-bold"
                       v-model="formData.expected_end_date"
                     />
                  </div>
               </div>

               <div class="space-y-2">
                  <label class="text-[10px] font-black text-on-surface-variant uppercase tracking-widest pl-1">Thời hạn thu hồi (Mặc định 80%)</label>
                  <div class="flex items-center gap-4">
                     <input 
                       type="range" min="0.5" max="1.0" step="0.05"
                       class="flex-1 accent-primary"
                       v-model.number="formData.recovery_deadline_ratio"
                     />
                     <span class="font-black text-primary w-12">{{ formData.recovery_deadline_ratio * 100 }}%</span>
                  </div>
               </div>

               <div class="space-y-4 pt-4 border-t border-outline">
                  <div class="flex items-center justify-between">
                     <label class="text-[10px] font-black text-on-surface-variant uppercase tracking-widest pl-1">Dự tính các lần thanh toán</label>
                     <button type="button" @click="addPaymentPlan" class="text-[10px] font-black text-primary uppercase tracking-widest hover:underline flex items-center gap-1">
                        <Plus class="w-3 h-3" /> THÊM LẦN THANH TOÁN
                     </button>
                  </div>
                  
                  <div class="space-y-3">
                     <div v-for="(plan, index) in formData.payment_plan" :key="index" class="p-4 bg-surface-container-low border border-outline rounded-2xl space-y-3 relative group">
                        <button type="button" @click="removePaymentPlan(index)" class="absolute top-2 right-2 p-1 text-on-surface-variant/50 hover:text-error hover:bg-error/10 rounded-full transition-colors opacity-0 group-hover:opacity-100">
                           <X class="w-4 h-4" />
                        </button>
                        
                        <div class="flex items-center gap-2">
                           <div class="w-6 h-6 rounded-full bg-primary/10 text-primary flex items-center justify-center text-[10px] font-black">
                              {{ index + 1 }}
                           </div>
                           <span class="text-xs font-bold text-on-surface">Thanh toán lần {{ index + 1 }}</span>
                        </div>
                        
                        <div class="grid grid-cols-3 gap-4">
                           <div class="space-y-1">
                              <label class="text-[8px] font-black text-on-surface-variant uppercase tracking-widest">Ngày thanh toán</label>
                              <input type="date" required v-model="plan.date" class="w-full px-3 py-2 bg-white border border-outline rounded-lg text-xs font-bold focus:ring-1 focus:ring-primary outline-none" />
                           </div>
                           <div class="space-y-1">
                              <label class="text-[8px] font-black text-on-surface-variant uppercase tracking-widest">Số tiền ($)</label>
                              <input type="number" required v-model.number="plan.amount" class="w-full px-3 py-2 bg-white border border-outline rounded-lg text-xs font-bold text-primary focus:ring-1 focus:ring-primary outline-none" />
                           </div>
                           <div class="space-y-1">
                              <label class="text-[8px] font-black text-on-surface-variant uppercase tracking-widest">Thu ứng ($)</label>
                              <input type="number" required v-model.number="plan.recovered" class="w-full px-3 py-2 bg-white border border-outline rounded-lg text-xs font-bold text-emerald-600 focus:ring-1 focus:ring-primary outline-none" />
                           </div>
                        </div>
                     </div>
                     <div v-if="formData.payment_plan.length === 0" class="text-xs text-center py-4 bg-surface-container-low border border-dashed border-outline rounded-2xl text-on-surface-variant font-medium">
                        Chưa có dự tính thanh toán nào
                     </div>
                  </div>
               </div>

               <div class="pt-4">
                  <button class="w-full py-5 bg-primary text-white rounded-2xl font-black shadow-2xl shadow-primary/30 hover:-translate-y-1 transition-all flex items-center justify-center gap-3" type="submit">
                     <Check class="w-6 h-6" />
                     XÁC NHẬN TẠO DỰ ÁN
                  </button>
               </div>
            </form>
         </div>
      </div>
    </div>
  </NavigationLayout>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { supabase } from '../../lib/supabase'
import NavigationLayout from '@/components/NavigationLayout.vue'
import { Rocket, Plus, Search, Calendar, DollarSign, ArrowRight, X, Check, Users, Trash2 } from 'lucide-vue-next'
import { usePermissions } from '../composables/usePermissions'

const { can } = usePermissions()

const projects = ref<any[]>([])
const loading = ref(true)
const isModalOpen = ref(false)
const formData = ref({
  name: '',
  contract_value: 0,
  start_date: new Date().toISOString().split('T')[0],
  end_date: '',
  expected_end_date: '',
  advance_rate: 0.3,
  recovery_deadline_ratio: 0.8,
  payment_plan: [] as Array<{ sequence: number, date: string, amount: number, recovered: number }>
})

async function deleteProject(id: string) {
  if (confirm("Bạn có chắc chắn muốn xóa dự án này? Thao tác này sẽ loại bỏ dự án khỏi các thống kê.")) {
    const { error } = await supabase.from('projects').update({ is_deleted: true }).eq('id', id);
    if (error) {
      alert("Lỗi khi xóa: " + error.message);
    } else {
      fetchProjects();
    }
  }
}

function addPaymentPlan() {
  formData.value.payment_plan.push({
    sequence: formData.value.payment_plan.length + 1,
    date: new Date().toISOString().split('T')[0],
    amount: 0,
    recovered: 0
  })
}

function removePaymentPlan(index: number) {
  formData.value.payment_plan.splice(index, 1)
  // Re-sequence
  formData.value.payment_plan.forEach((p, i) => p.sequence = i + 1)
}

async function fetchProjects() {
  loading.value = true
  const { data } = await supabase
    .from('projects')
    .select('*')
    .eq('is_deleted', false)
    .order('created_at', { ascending: false })
  
  if (data) projects.value = data
  loading.value = false
}

async function handleSubmit() {
  try {
    const advance_amount = formData.value.contract_value * formData.value.advance_rate
    
    const insertData: any = {
      name: formData.value.name,
      contract_value: formData.value.contract_value,
      start_date: formData.value.start_date,
      advance_rate: formData.value.advance_rate,
      advance_amount,
      recovery_deadline_ratio: formData.value.recovery_deadline_ratio,
      payment_plan: formData.value.payment_plan
    }

    if (formData.value.end_date) insertData.end_date = formData.value.end_date
    if (formData.value.expected_end_date) insertData.expected_end_date = formData.value.expected_end_date

    const { data, error } = await supabase.from('projects').insert([insertData]).select()

    if (error) {
      alert('Lỗi: ' + error.message)
    } else {
      isModalOpen.value = false
      formData.value = {
        name: '',
        contract_value: 0,
        start_date: new Date().toISOString().split('T')[0],
        end_date: '',
        expected_end_date: '',
        advance_rate: 0.3,
        recovery_deadline_ratio: 0.8,
        payment_plan: []
      }
      fetchProjects()
    }
  } catch (err: any) {
    alert('Đã xảy ra lỗi không xác định.')
  }
}

onMounted(() => {
  fetchProjects()
})
</script>
